### ISSUE TITLE
Installation instruction why with -D in the end?

### ISSUE THREAD

**Issue by Ekkstein** [anthonygore/vue-router-user-roles#12]
First off, sorry for opening this issue for this, but I didn't see a way to mention this other wise.

Why is there a -D appended in the installation instructions? I understand -D flags for installations in dev-dependencies, but I would like this functionality to be available in production as well. Am I missing something?

**Comment by anthonygore** [comment]
I think it was just a mistake...I've removed it now.

**Comment by mzhukovs** [comment]
@anthonygore  fyi the npm page wasn't updated for this
