### ISSUE TITLE
Handle dynamic parameter routes

### ISSUE THREAD

**Issue by mzhukovs** [anthonygore/vue-router-user-roles#15]
Thanks for this library - it is very useful. One feature request please:

**Handle dynamic routes.** My app requires no logins, because it's using Windows Auth and AD. I have a Vue component that handles errors, which takes a route parameter for the error code, e.g. for unauthorized user I would pass 403 as the code for Forbidden, and the page would display something specific relating to that issue (want to request access? blah blah):

          {
            role: "guest",
            access: false,
            redirect: "oops/403"
          }

But it seems this does not work.

Your consideration would be much appreciated.

**Comment by danghh-1998** [comment]
You can define a route with name `forbidden` 

```js
{
    path: "/oops/403",
    name "forbidden"
}
```

For unauthorized user:

```js
{
    role: "guest",
    access: false,
    redirect: "forbidden"
}
```

`redirect` use route name only https://github.com/anthonygore/vue-router-user-roles/blob/902e5fb1b22c866745297485c763f0fc2d893009/src/RouteProtect.js#L23

I hope this can help you

**Comment by mzhukovs** [comment]
Nice, easy enough... thanks!
