### ISSUE TITLE
Read me part is missing !!!

### ISSUE THREAD

**Issue by kerimkuscu** [anthonygore/vue-router-user-roles#9]
### vue & vue-router-permissions version
vue: 2.6.4
vue-router: ^3.0.2

### Reproduction Link
Out of the box

### Steps to reproduce
Setup access per documentation. Notice how when you have a protected route, it will flash before redirecting when access is not allowed.

### What is Expected?
read me part is missing.

### What is actually happening?
Correct the read me part. Because npm package name is missing.

![e9faca86-fd20-4fa8-b86a-b92a2debb2cb](https://user-images.githubusercontent.com/43302726/56364396-1cd44300-61f7-11e9-94eb-40f399811d88.png)

**Comment by anthonygore** [comment]
Thanks, will do
